-- 시퀀스 생성
CREATE SEQUENCE DAY_ATTD_CODE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE REST_ATTD_CODE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE newBoard_seq2 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE boardFile_seq2 START WITH 1 INCREMENT BY 1;

-- 1. 시스템/공통 테이블
CREATE TABLE NEWBOARD (
    BOARD_SEQ NUMBER PRIMARY KEY,
    REF_SEQ NUMBER,
    REPLY_SEQ NUMBER,
    NAME VARCHAR(50),
    TITLE VARCHAR(200),
    CONTENT CLOB,
    HIT NUMBER DEFAULT 0,
    REG_DATE VARCHAR(20)
);

CREATE TABLE BOARDFILE (
    FILE_SEQ NUMBER PRIMARY KEY,
    BOARD_SEQ NUMBER,
    FILENAME VARCHAR(200),
    TEMPFILENAME VARCHAR(200),
    FOREIGN KEY (BOARD_SEQ) REFERENCES NEWBOARD(BOARD_SEQ) ON DELETE CASCADE
);

CREATE TABLE DEPT (
    DEPT_CODE VARCHAR(10) PRIMARY KEY,
    DEPT_NAME VARCHAR(50)
);

CREATE TABLE POSITION (
    POSITION_CODE VARCHAR(10) PRIMARY KEY,
    POSITION VARCHAR(50),
    BASE_SALARY VARCHAR(20)
);

CREATE TABLE CODE (
    CODE_NUMBER VARCHAR(20) PRIMARY KEY,
    CODE_NAME VARCHAR(100)
);

CREATE TABLE DETAIL_CODE (
    DETAIL_CODE_NUMBER VARCHAR(20) PRIMARY KEY,
    CODE_NUMBER VARCHAR(20),
    DETAIL_CODE_NAME VARCHAR(100),
    DETAIL_CODE_NAME_KR VARCHAR(100)
);

CREATE TABLE HOLIDAY (
    APPLY_DAY VARCHAR(20) PRIMARY KEY,
    HOLIDAY_NAME VARCHAR(50),
    NOTE VARCHAR(100)
);

CREATE TABLE MENU (
    MENU_CODE VARCHAR(20) PRIMARY KEY,
    MENU_NAME VARCHAR(50),
    URL VARCHAR(100),
    SUPER_MENU_CODE VARCHAR(20),
    NAVBAR_NAME VARCHAR(50)
);

-- 2. 인사관리 테이블
CREATE TABLE EMP (
    EMP_CODE VARCHAR(10) PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    PASSWORD VARCHAR(100),
    BIRTHDATE DATE,
    GENDER VARCHAR(10),
    MOBILE_NUMBER VARCHAR(20),
    ADDRESS VARCHAR(200),
    DETAIL_ADDRESS VARCHAR(200),
    POST_NUMBER VARCHAR(10),
    EMAIL VARCHAR(100),
    LAST_SCHOOL VARCHAR(100),
    IMG_EXTEND VARCHAR(10),
    POSITION_CODE VARCHAR(10),
    DEPT_CODE VARCHAR(10),
    AUTHORITY VARCHAR(10)
);

CREATE TABLE WORK_INFO (
    EMP_CODE VARCHAR(10),
    WORK_INFO_DAYS VARCHAR(20),
    HIREDATE DATE,
    RETIRE_DATE DATE,
    OCCUPATION VARCHAR(50),
    EMPLOYMENT_TYPE VARCHAR(50),
    HOBONG VARCHAR(20),
    SALARY_TYPE VARCHAR(50),
    DEPT_NAME VARCHAR(50),
    PRIMARY KEY (EMP_CODE, HIREDATE)
);

CREATE TABLE LICENSE_INFO (
    EMP_CODE VARCHAR(10),
    LICENSE_CODE VARCHAR(20),
    LICENSE_NAME VARCHAR(100),
    GET_DATE DATE,
    EXPIRE_DATE DATE,
    LICENSE_LEVEL VARCHAR(50),
    LICENSE_CENTER VARCHAR(100),
    ISSUE_NUMBER VARCHAR(50),
    PRIMARY KEY (EMP_CODE, LICENSE_CODE)
);

CREATE TABLE FAMILY_INFO (
    EMP_CODE VARCHAR(10),
    FAMILY_CODE VARCHAR(20),
    FAMILY_NAME VARCHAR(50),
    RELATION VARCHAR(50),
    BIRTHDATE DATE,
    LIVE_TOGETHER VARCHAR(10),
    PRIMARY KEY (EMP_CODE, FAMILY_CODE)
);

CREATE TABLE EMP_EVAL (
    EMP_CODE VARCHAR(10) PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    APPLY_DAY VARCHAR(20),
    ACHIEVEMENT NUMBER,
    ABILITY NUMBER,
    ATTITUDE NUMBER,
    NOTE VARCHAR(200)
);

-- 3. 근태관리 테이블
CREATE TABLE DAY_ATTD (
    EMP_CODE VARCHAR(10),
    DAY_ATTD_CODE VARCHAR(20) PRIMARY KEY,
    APPLY_DAY DATE,
    ATTD_TYPE_CODE VARCHAR(10),
    ATTD_TYPE_NAME VARCHAR(50),
    TIME NUMBER
);

CREATE TABLE REST_ATTD (
    EMP_CODE VARCHAR(10),
    REST_ATTD_CODE VARCHAR(20) PRIMARY KEY,
    REST_TYPE_CODE VARCHAR(10),
    REST_TYPE_NAME VARCHAR(50),
    REQUEST_DATE DATE,
    START_DATE DATE,
    END_DATE DATE,
    CAUSE VARCHAR(200),
    APPL_STUS VARCHAR(10),
    REJECT_CAUSE VARCHAR(200),
    COST NUMBER
);

-- 4. 급여관리 테이블
CREATE TABLE BASE_SALARY (
    POSITION_CODE VARCHAR(10) PRIMARY KEY,
    POSITION VARCHAR(50),
    BASE_SALARY NUMBER,
    HOBONG_RATIO NUMBER
);

CREATE TABLE BASE_EXT_SAL (
    EXT_SAL_CODE VARCHAR(10) PRIMARY KEY,
    EXT_SAL_NAME VARCHAR(50),
    RATIO NUMBER
);

CREATE TABLE SOCIAL_INS (
    "YEAR" VARCHAR(10) PRIMARY KEY,
    HEALTH_INS_RATIO NUMBER,
    PENSION_INS_RATIO NUMBER,
    EMPLOYMENT_INS_RATIO NUMBER,
    LONG_TERM_CARE_INS_RATIO NUMBER
);

-- 5. 기초 데이터 삽입
INSERT INTO DEPT VALUES ('D1', '인사부');
INSERT INTO DEPT VALUES ('D2', '개발부');
INSERT INTO DEPT VALUES ('D3', '영업부');

INSERT INTO POSITION VALUES ('P1', '사원', '2000000');
INSERT INTO POSITION VALUES ('P2', '대리', '2500000');
INSERT INTO POSITION VALUES ('P3', '과장', '3000000');

-- 테스트용 계정 (사원코드, 이름, 비밀번호, 직급코드, 부서코드, 권한)
INSERT INTO EMP (EMP_CODE, EMP_NAME, PASSWORD, POSITION_CODE, DEPT_CODE, AUTHORITY) 
VALUES ('admin', 'admin', '1234', 'P3', 'D1', 'admin');
INSERT INTO EMP (EMP_CODE, EMP_NAME, PASSWORD, POSITION_CODE, DEPT_CODE, AUTHORITY) 
VALUES ('A490071', '인사사원', '1234', 'P1', 'D1', 'user');

INSERT INTO CODE VALUES ('CO-01', '근태구분');
INSERT INTO DETAIL_CODE VALUES ('ADC001', 'CO-01', '출근', '출근');
INSERT INTO DETAIL_CODE VALUES ('ADC002', 'CO-01', '퇴근', '퇴근');

INSERT INTO BASE_SALARY VALUES ('P1', '사원', 2000000, 0.1);
INSERT INTO BASE_SALARY VALUES ('P2', '대리', 2500000, 0.12);

INSERT INTO SOCIAL_INS VALUES ('2024', 0.0343, 0.045, 0.008, 0.1152);

-- 메뉴 데이터
-- 1. 인사관리 (대메뉴)
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU00', '인사관리', '#', NULL, '인사관리');
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU01', '사원등록', '/empmgmt/empReg/view', 'MENU00', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU02', '사원목록', '/empmgmt/empDetail/view', 'MENU00', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU09', '사원평가', '/empmgmt/empEval/view', 'MENU00', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU10', '증명서관리', '/empmgmt/certificate/view', 'MENU00', NULL);

-- 2. 근태관리 (대메뉴)
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU03', '근태관리', '#', NULL, '근태관리');
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU04', '일근태등록', '/attd/dailyAttnd/view', 'MENU03', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU05', '근태외신청', '/attd/excusedAttnd/view', 'MENU03', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU06', '근태승인관리', '/attd/attndApproval/view', 'MENU03', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU11', '연차관리', '/attd/annualLeaveMgt/view', 'MENU03', NULL);

-- 3. 급여관리 (대메뉴)
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU07', '급여관리', '#', NULL, '급여관리');
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU08', '급여계산', '/salary/fullTimeSal/view', 'MENU07', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU12', '급여기준관리', '/salary/baseSalMgt/view', 'MENU07', NULL);
INSERT INTO MENU (MENU_CODE, MENU_NAME, URL, SUPER_MENU_CODE, NAVBAR_NAME) VALUES ('MENU13', '사회보험관리', '/salary/socialIns/view', 'MENU07', NULL);
